config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  # Exercises
  post 'exercises/new'
  get '/calendar', to: 'exercises#calendar'

  # Users
  resources :users
  get '/signup', to: 'users#new'
  get '/leaderboard', to: 'users#leaderboard'

  # Sessions
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  # Static Pages
  get 'static_pages/index'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  # Posts
  resources :posts, :only => [:new, :create, :index]
  get '/messages', to: 'posts#index'

end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  has_many :posts,      dependent: :destroy
  has_many :exercises,  dependent: :destroy

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :name, presence: true, length: { maximum: 50 }

  before_save :downcase_email
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, length: { maximum: 255 }, 
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }



  
  # Returns hash digest of given string
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def User.losers
    # set 'limit' to monthly exercise count of 2nd from last user
    limit = User.monthly_count[-2][0] 
    losers = Array.new
    User.monthly_count.each do |arr|
      losers << arr if arr[0] <= limit
    end
    losers
  end

  def User.leaders
    # set 'limit' to monthly exercise count of 2nd place user
    limit = User.monthly_count[1][0]
    leaders = Array.new
    User.monthly_count.each do |arr|
      leaders << arr if arr[0] >= limit
      puts "#{arr[0]} limit: #{limit}"
    end
    leaders
  end

  private
  
  def downcase_email
    self.email = email.downcase
  end
  
  def User.monthly_count
    # Returns Array [Monthly Count, User Object] sorted by 
    # monthly exercise count high to low
    a = Array.new
    User.all.each do |user|
      if user.exercises.this_month.count > 0
        a << [user.exercises.this_month.count, user]
      end
    end
    a.sort.reverse!
  end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user,  only: [:index, :edit, :update, :destroy, :show]
  before_action :correct_user,    only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def leaderboard
    @leaders = User.leaders
    @losers = User.losers
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:info] = "Welcome, #{@user.name}!"
      redirect_to root_url
    else
      # Errors rendered by '_users_form'
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page], per_page: 5).order('created_at desc')
    @exercises = @user.exercises
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "User Profile Successfully Updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash.now[:success] = "User deleted"
    redirect_to users_url
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end



end

app/helpers/users_helper.rb
module UsersHelper

  def gravitar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/users/_user_count.html.erb
<section class="user_info">
  <ul class="users">
    <h3>
      (<%= user[0] %>)
      <%= link_to user[1].name, user_path(user[1].id) %>
    </h3>
  </ul>
</section>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<h1>Edit Profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>
      <%= render 'shared/form_error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %><br />

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %><br />

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %><br />
      
      <%= f.submit "Submit", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3 top-padding-60">
  <h2>The following <strong><u>CANNOT</u></strong> be undone. <strong>Proceed with caution</strong></h2>
    <%= form_for(@user, method: :delete) do |f| %>
      <%= f.submit "Delete Account", class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete your account?' } %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "All Users") %>
<h1>All Users (<%= @users.count %>)</h1>

<section class="user_info">
  <% @users.each do |user| %>
    <ul class="users">
      <h3>
        <%= gravitar_for(user, size: 35) %>
        <%= link_to user.name, user_path(user) %>
        <% if current_user.admin? %>
          <%= link_to "  ||  Delete User", user, method: :delete, data: { confirm: "Are you sure you want to delete this user?" } %>
        <% end %>
      </h3>
    </ul>
  <% end %>
</section>

app/views/users/leaderboard.html.erb
<% provide(:title, "Leaderboard") %>
<h1>Leaderboard</h1>

<% @leaders.each do |user| %>
  <%= render partial: 'user_count', :locals => { user: user } %>
<% end %>


<h1>Loserboard</h1>

<% @losers.each do |user| %>
  <%= render partial: 'user_count', :locals => { user: user } %>
<% end %>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>
<h1>New User</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

  <%= form_for(@user) do |f| %>
    <%= render 'shared/form_error_messages' %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %><br />

    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %><br />

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %><br />

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %><br />
    
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  <% end %>
  
  <h2>Already signed up? <%= link_to "Log in here", login_path %></h2>

  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
  <aside class="col-md-3"></aside>
  <aside class="col-md-1">
    <%= gravitar_for(@user, size: 100) %>
  </aside>
  <aside class="col-md-4">
    <section class="user_info">
      <h1><%= @user.name %></h1>
      <% if current_user == @user %>
        <h2><%= @user.email %></h2>
      <% end %>
    </section>
  </aside>
</div>

<div class="row">
  <!-- Display User Posts -->
  <div class="col-md-6">
      <% if @user.posts_count > 0 %>
        <h3>Your Posts (<%= @user.posts_count %>)</h3>
        <ol class="microposts">
          <%= render @posts %>
        </ol>
        <%= will_paginate @posts %>
      <% end %>
  </div>

  <!-- Display User Exercises -->
  <div class="col-md-6">
    <% if @user.exercise_count > 0 %>
      <h3>Your Exercise History (<%= @user.exercise_count %>)</h3>
      <ol class="microposts">
        <%= render @exercises %>
      </ol>
    <% end %>
  </div>
</div>