config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  # Exercises
  post 'exercises/new'
  get '/calendar', to: 'exercises#calendar'

  # Users
  resources :users
  get '/signup', to: 'users#new'
  get '/leaderboard', to: 'users#leaderboard'

  # Sessions
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  # Static Pages
  get 'static_pages/index'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  # Posts
  resources :posts, :only => [:new, :create, :index]
  get '/messages', to: 'posts#index'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Built by <a href="http://www.andyduss.com">Andy Duss</a>
  </small>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="https://github.com/mindovermiles262/exercise-tracker">Hack Me</a></li>
    </ul>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-light bg-primary">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to "Exercise Tracker", root_url, id: 'brand', class: 'navbar-brand' %>

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="glyphicon glyphicon-menu-hamburger"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if logged_in? %>
      <!-- Navbar if logged in:  -->
        <ul class="nav navbar-nav navbar-center">
          <li><%= link_to "Messages", messages_path, id: "link" %></li>
          <li><%= link_to "Leaderboard", leaderboard_path, id: "link" %></li>
          <li><%= link_to "Calendar", calendar_path, id: 'link' %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "I Exercised!", exercises_new_path(user_id: current_user.id, exercise_time: Time.zone.now, test: 'foobar'), :method=> :post, class: "emphasize btn btn-success" %></a></li>
          <% if current_user %>
            <li><%= link_to current_user.name, current_user, id: "link" %></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle bg-primary" id="link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-cog icon" aria-hidden="true"></i></a>
            <ul class="dropdown-menu">
              <li><%= link_to "All Users", users_path %></li>
              <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log Out", logout_path %></li>
            </ul>
          </li>
        </ul>
      <% else %>  
      <!-- Navbar as guest -->
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Sign Up Now", signup_path, id: "link", class: 'border-white-1' %></li>
          <li><%= link_to "Log In", login_path, id: "link" %></li>
        </ul>
      <% end %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%# Render Header %>
    <%= render 'layouts/nav' %>

     <%# Render Flash Messages %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
    </div>

    <%# Render Body %>
    <div class="container">
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>